version: '3.7'
volumes:
  static_files:
services:
  web:
    build:
      context: .
      dockerfile: dockerfile/prod/web/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - ./project:/project
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 project.wsgi -b 0.0.0.0:8000
  nginx:
    build:
      context: .
      dockerfile: dockerfile/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80